# Generated by Django 5.2.8 on 2026-01-09 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("patients", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MCReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("origin", models.CharField(max_length=100)),
                ("date", models.DateField()),
                (
                    "state_lab",
                    models.CharField(
                        choices=[("attached", "Attached"), ("not_done", "Not Done")]
                    ),
                ),
                (
                    "state_other",
                    models.CharField(
                        choices=[("attached", "Attached"), ("not_done", "Not Done")]
                    ),
                ),
                ("conclusion", models.CharField(max_length=1000)),
                ("recommendations", models.CharField(max_length=1000)),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="patients.patient",
                    ),
                ),
            ],
            options={
                "ordering": ["-date"],
            },
        ),
    ]
