# Generated by Django 5.2.8 on 2026-01-09 16:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mc_reports", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mcreport",
            name="conclusion",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="mcreport",
            name="recommendations",
            field=models.TextField(),
        ),
    ]
