# Generated by Django 5.2.8 on 2026-01-09 16:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mc_reports", "0002_alter_mcreport_conclusion_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mcreport",
            name="state_lab",
            field=models.CharField(
                choices=[("attached", "Attached"), ("not_done", "Not Done")],
                verbose_name="Laboratory test results",
            ),
        ),
        migrations.AlterField(
            model_name="mcreport",
            name="state_other",
            field=models.CharField(
                choices=[("attached", "Attached"), ("not_done", "Not Done")],
                verbose_name="Results of other special studies",
            ),
        ),
    ]
