# Generated by Django 5.2.8 on 2026-01-21 10:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("patients", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="XRaysExamination",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("examination", models.CharField(max_length=200)),
                ("date", models.DateField()),
                ("medical_record_number", models.CharField(blank=True, max_length=20)),
                ("technical_parameters", models.TextField()),
                ("description", models.TextField()),
                ("conclusion", models.TextField()),
                ("recommendations", models.TextField()),
                ("doctor_name", models.CharField(max_length=30)),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="patients.patient",
                    ),
                ),
            ],
        ),
    ]
