# Generated by Django 5.2.8 on 2026-01-22 10:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("x_rays", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="xraysexamination",
            options={"ordering": ["-date"]},
        ),
    ]
