# Generated by Django 5.2.8 on 2026-01-29 14:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("x_rays", "0002_alter_xraysexamination_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="xraysexamination",
            name="eed",
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
