server {
    listen 80;
    server_name dj-digitalclinic.jeeves-api.tech;

    # Requests to /static/ are served directly from the /static/ directory
    location /static/ {
        alias /usr/share/nginx/static/;
        expires 7d;
    }
    location /media/ {
        alias /usr/share/nginx/media/;
        expires 7d;
    }

    location / {
        proxy_pass http://dj:8000;

        # Information about the original sender
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
