# Generated by Django 5.2.8 on 2025-11-20 14:20

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Patient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "full_name",
                    models.CharField(
                        max_length=40, unique=True, verbose_name="full name"
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[("male", "Male"), ("female", "Female")],
                        verbose_name="gender",
                    ),
                ),
                ("dob", models.DateField(verbose_name="date of birth")),
                (
                    "height",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="height (m)",
                    ),
                ),
                (
                    "weight",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="weight (kg)",
                    ),
                ),
                (
                    "waist_circ",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="waist circumference (cm)",
                    ),
                ),
                (
                    "phone1",
                    models.CharField(blank=True, max_length=20, verbose_name="phone 1"),
                ),
                (
                    "phone2",
                    models.CharField(blank=True, max_length=20, verbose_name="phone 2"),
                ),
                (
                    "address",
                    models.CharField(
                        blank=True,
                        help_text="Region District City Street Building Apartment",
                        max_length=100,
                        verbose_name="address",
                    ),
                ),
                (
                    "job_title",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="job title"
                    ),
                ),
                ("disp", models.TextField(blank=True, verbose_name="dispansery group")),
                (
                    "last_disp",
                    models.DateField(
                        blank=True, null=True, verbose_name="last dispanserisation"
                    ),
                ),
                (
                    "last_colonoscopy",
                    models.DateField(
                        blank=True, null=True, verbose_name="last colonoscopy"
                    ),
                ),
            ],
        ),
    ]
