# Generated by Django 5.2.8 on 2026-01-21 12:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("patients", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="patient",
            options={"ordering": ["full_name"]},
        ),
    ]
