# Generated by Django 5.2.8 on 2025-11-21 12:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Test",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("units", models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="TestAgeGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("max_age", models.PositiveSmallIntegerField()),
                ("male_min", models.DecimalField(decimal_places=3, max_digits=6)),
                ("male_max", models.DecimalField(decimal_places=3, max_digits=6)),
                ("female_min", models.DecimalField(decimal_places=3, max_digits=6)),
                ("female_max", models.DecimalField(decimal_places=3, max_digits=6)),
                (
                    "test",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="tests.test"
                    ),
                ),
            ],
            options={
                "ordering": ["max_age"],
            },
        ),
    ]
