# Generated by Django 5.2.8 on 2026-02-06 09:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("colonoscopy", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="colonoscopyreport",
            old_name="ansesthetist",
            new_name="anesthetist",
        ),
    ]
