# Generated by Django 5.2.8 on 2026-02-06 16:23

import apps.colonoscopy.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("colonoscopy", "0002_rename_ansesthetist_colonoscopyreport_anesthetist"),
    ]

    operations = [
        migrations.AlterField(
            model_name="photoprotocolimage",
            name="image",
            field=models.ImageField(
                upload_to=apps.colonoscopy.models.PhotoProtocolImage.get_upload_path
            ),
        ),
    ]
