# Generated by Django 5.2.8 on 2026-02-11 12:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("colonoscopy", "0003_alter_photoprotocolimage_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="colonoscopyreport",
            name="next_colonoscopy",
            field=models.CharField(
                choices=[
                    ("4y", "NBCSP in 4 years"),
                    ("2y", "Lynch syndrome - repeat colonoscopy after 2 years"),
                    (
                        "0y",
                        "Once confirmed, pathology will schedule the next colonoscopy.",
                    ),
                ]
            ),
        ),
    ]
