# Generated by Django 5.2.8 on 2026-02-12 14:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("colonoscopy", "0004_alter_colonoscopyreport_next_colonoscopy"),
    ]

    operations = [
        migrations.RenameField(
            model_name="colonoscopyreport",
            old_name="organisation",
            new_name="organization",
        ),
    ]
