# Generated by Django 5.2.8 on 2026-02-25 14:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("colonoscopy", "0005_rename_organisation_colonoscopyreport_organization"),
    ]

    operations = [
        migrations.RenameField(
            model_name="colonoscopyreport",
            old_name="adversary_events",
            new_name="adverse_events",
        ),
        migrations.AlterField(
            model_name="colonoscopyreport",
            name="time",
            field=models.TimeField(blank=True, null=True),
        ),
    ]
