# Generated by Django 5.2.8 on 2026-04-24 13:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "colonoscopy",
            "0006_rename_adversary_events_colonoscopyreport_adverse_events_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="colonoscopyreport",
            name="biopsy_referral",
            field=models.PositiveIntegerField(),
        ),
    ]
