# Generated by Django 5.2.8 on 2026-05-12 15:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lab", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="testresult",
            name="value",
            field=models.DecimalField(decimal_places=3, max_digits=8),
        ),
    ]
